### ISSUE TITLE
Remote host not reconnecting after power off

### ISSUE THREAD

**Issue by Londoneye02** [ualex73/monitor_docker#103]
I have a installation made on a raspberry which is monitoring both the raspberry itself and also a remote host running Debian 

Bellow is the configuration

```
- name: Docker_Raspberry
  containers:
     - pihole
     - nginx_manager
     - duplicati
     - grafana
     - homer
  rename:
    pihole: PiHole
    nginx_manager: Nginx Proxy Manager
    duplicati: Duplicati
    grafana: Grafana
    homer: Homer

  monitored_conditions:
    - version
    - containers_running
    - containers_total
    - state
    - status
    - memory
    - network_total_up


- name: Docker_DebianServer
  url: tcp://192.168.1.117:2375
  containers:
     - jellyfin 
  rename:
    jellyfin: Jellyfin

  monitored_conditions:
   - version
   - containers_running
   - containers_total
   - state
   - status
   - memory
   - network_total_up
   - network_speed_up
   - network_speed_down
```

It works fine if I start the raspberry after the Debian Server. But if I turn off the remote server, It does not receive any data from It when it comes back live.

![Screenshot_20220615-182042-183](https://user-images.githubusercontent.com/29100907/173877118-b0e40e20-3f35-4249-b2ff-3d3c22a086a7.png)

Is it the normal behaviour, or do I have anything wrong on the configuration?? Most of the times, it does not work. In a very few occasion, it works

Thank you for your time

**Comment by ualex73** [comment]
I will test this soon, I am not also not sure what the behavior should be (I dependent on the underlying library).

**Comment by RK62** [comment]
Same on my system. When the remote docker_proxy restarts, the integration will lost the connection and I have to restart Home Assistant to renable ist:
```
2024-07-06 10:19:15.279 ERROR (MainThread) [custom_components.monitor_docker.helpers] [xxxxx] bitwarden: Container not available anymore (3a) (DockerError(900, 'Cannot connect to Docker Engine via tcp://xxxxx.lan:2375 [Server disconnected]'))
2024-07-06 10:19:15.280 ERROR (MainThread) [custom_components.monitor_docker.helpers] [xxxxx] dockerproxy_xxxxx: Container not available anymore (3a) (DockerError(900, 'Cannot connect to Docker Engine via tcp://xxxxx.lan:2375 [Server disconnected]'))
2024-07-06 10:19:18.149 ERROR (MainThread) [custom_components.monitor_docker.helpers] [xxxxx]: run_docker_events loop ended
2024-07-06 10:20:21.219 ERROR (MainThread) [custom_components.monitor_docker.helpers] [xxxxx]: Trying to get a not existing container adminer
2024-07-06 10:20:21.219 ERROR (MainThread) [custom_components.monitor_docker.switch] Service restart failed, container 'adminer'does not exist 
```

**Comment by ualex73** [comment]
@RK62 this is also with v1.19?

**Comment by RK62** [comment]
@ualex73 Yes, I installed & try it today with... 
- Custom Monitor Docker component for Home Assistant v1.19 
- ghcr.io/tecnativa/docker-socket-proxy:0.1.2
- HA-Core 2024.7.1

**Comment by nobodyspecial** [comment]
I can confirm this. The monitor_docker component never attempts to reconnect to a remote host if it loses the connection. 

Is there any way to restart the component without restarting home assistant?

**Comment by sstratoti** [comment]
I'm seeing this as well. If it loses connection it can't seem to re-establish, even though it is running. Restart of HA fixes it temporarily, and then I see errors again and lose current status.

**Comment by ualex73** [comment]
I am aware of the issue, still investigating how we can make it work (the problem is a bit in the underlying library I use)

**Comment by sstratoti** [comment]
Sounds like you're on it, but I ust wanted to add - tried increasing my timeout through haproxy.cfg file mapped into tecnativa/docker-socket-proxy. Increased the timeouts to 1m with the same issue. 

Thank you for looking into this!

Also I think tecnativa/docker-socket-proxy recently (last few weeks) updated to haproxy 3.0 in their main branch? Not sure if that matters either.

**Comment by ualex73** [comment]
Can you try the 1.20b0 (pre-release)? It should resolve this.

**Comment by pww217** [comment]
I tried this having been following this thread. 

Good news: it seems to reconnect! I rebooted and after the container was up for idk, 30 seconds or so it reconnected.

Bad news: The host machine where HA and other containers live no longer works. I'm not sure if there was a breaking change but I didnt change my HA docker-compose nor my monitor_docker config, and it worked great before.

Here's some snippets if it helps:

```yaml
version: '3.8'
services:
    homeassistant:
        ports:
          - '8123:8123'
        network_mode: host
        container_name: homeassistant
        image: "ghcr.io/home-assistant/home-assistant:stable"
        environment:
          - TZ=America/Chicago
        volumes:
          ...
          # Required for Monitor Docker integration
          - /var/run/docker.sock:/var/run/docker.sock
          ...
        # Maps the Zigbee controller
        restart: unless-stopped
        privileged: false
```

```yaml
monitor_docker:
  # This remains unchanged and worked before
  - name: Docker - Media
    scan_interval: 120
    # containers_exclude:
    switchenabled: false
    buttonenabled: false
    monitored_conditions:
      # - allinone
      # - version
      - containers_running
      - containers_total
      ...

  # This one works great now!
  - name: Docker - Raspi
    url: http://10.75.50.10:2375
    scan_interval: 120
    ...
```
