### ISSUE TITLE
How to configure ha for remote docker on debian?

### ISSUE THREAD

**Issue by ttmader** [ualex73/monitor_docker#108]
Hi,

I am currently controlling the dockers with rest through port 8126.

- platform: rest
  resource: http://ipdocker:8126/container/pihole
  name: PiHole
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

If I configure that port in monitor_docker it does not detect it.

How can I do it to monitor it?

Thanks.

**Comment by ualex73** [comment]
The example you supply, is not compatible with the "monitor_docker". You need to expose the docker API of your Debian node to the "monitor_docker", so it needs to be something like:
```
- name: RemoteDocker
    url: tcp://10.0.0.1:2376
    containers:
    ...
```

The switch on/off will be automatically added in HA.

**Comment by poudenes** [comment]
Hi,

I have Home Assistant (HAOS) installed in my RPi48GB. Everything runs perfect.
I have lot of docker containers running on my Synology NAS DS220+

My HA is 192.168.100.24 and my NAS is 192.168.100.62

How can I monitor those dockers into my HA?

Tried this but get a error that it can't connect.
```
- name: RemoteDocker
    url: tcp://192.168.100.62:2376
    containers:
    ...
```
