### ISSUE TITLE
Error "Instance Docker is duplicate" after updating to HA 2024.4.0

### ISSUE THREAD

**Issue by purnhar** [ualex73/monitor_docker#142]
After updating HA to version 2024.4.0 the integration does not start up anymore. The following error is shown in the logs:

```
Logger: custom_components.monitor_docker
Source: custom_components/monitor_docker/__init__.py:150
integration: monitor_docker ([documentation](https://github.com/ualex73/monitor_docker), [issues](https://github.com/ualex73/monitor_docker/issues))
First occurred: 06:47:12 (1 occurrences)
Last logged: 06:47:12

Instance Docker is duplicate, please assign an unique name
```

The integration is installed via HACS, HA itself runs as Docker container.

The following configuration is used:

```
monitor_docker:
  - name: Docker
  - containers:
      - adguardhome
      - duckdns
      - homeassistant
      - mosquitto
      - proxymanager
      - watchtower
  - monitored_conditions:
      - containers_cpu_percentage
      - containers_memory
      - containers_memory_percentage
      - state
      - cpu_percentage
      - memory
      - memory_percentage
      - network_speed_up
      - network_speed_down
```
