### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by nytram-md** [ualex73/monitor_docker#15]
If the switches have some kind of security feature on them please ?

Its too easy to turn off a container. So maybe a PIN option of long press feature would be handy for mobile phone.

Thanks again

Martyn

**Comment by ualex73** [comment]
From the custom_component i can't add a security feature. What is in my mind is to make it possible to disable the switch completely for a specific container.

If you like to have some security, you need to use a custom card like https://github.com/iantrich/restriction-card.

I added the following to my configuration:
```
      - card:
          entity: switch.docker_hass
        restrictions:
          block: true
        type: custom:restriction-card
        row: true
      - card:
          entity: switch.docker_influxdb
        restrictions:
          block: true
        type: custom:restriction-card
        row: true
      - switch.docker_mosquitto
      - switch.docker_motioneye
```

Thanks for reporting it, i will add a similar example to the README.
