### ISSUE TITLE
Cannot connect to Docker Engine since v1.19

### ISSUE THREAD

**Issue by kcofoni** [ualex73/monitor_docker#153]
Hello,

After upgrading to v1.19 (running HA 2027.7.1), I cannot connect any more to my docker engine.
I got the following error when starting home assistant in the log file:

`2024-07-06 01:48:02.797 ERROR (MainThread) [custom_components.monitor_docker] Failed Docker connect: DockerError(900, "Cannot connect to Docker Engine via tcp://<my_ip>:2376 [Cannot connect to host <my_ip>:2376 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unsuitable certificate purpose (_ssl.c:1000)')]]")`

Here is the docker configuration in my configuration.yaml file:

```
monitor_docker:
  - name: Docker Prod
    url: tcp://<my_ip>:2376
    certpath: /config/docker_certs
    monitored_conditions:
      - allinone

```

<my_ip> being replaced by a real lan ip address

My certificate files have been properly generated for a while. It was perfectly working with the previous version (in particular v1.8). Coming back to v1.18 makes it work again.
