### ISSUE TITLE
Feature Request: Monitored Conditions as attrubutes inside docker switch 

### ISSUE THREAD

**Issue by VirtualL** [ualex73/monitor_docker#16]
Hi, Currently, all the Monitored Conditions are made a new entity.
E.G:  for Docker "mosquito" this entity are made:
switch.docker_mosquitto - switch docker ON/OFF
sensor.docker_mosquitto_memory
sensor.docker_mosquitto_state
sensor.docker_mosquitto_status
and so on... (sensor.docker_mosquitto_XXX)

There is an option to add all of these sensors on the main "switch" as attributes, for each docker?
I don't like 20 sensors for each docker in my system. (8X20 its a lot of entities)

also, if someone wants to use these as sensors, he can do it like this:
```
# Example configuration.yaml entry
sensor:
  - platform: template
    sensors:
      docker_mosquitto_memory:
        friendly_name: "MQTT Memory Usage"
        value_template: '{{ states.switch.docker_mosquitto.attributes.memory }}'
      docker_mosquitto_memory:
        friendly_name: "MQTT State"
        value_template: '{{ states.switch.docker_mosquitto.attributes.state }}'
```

Also, it will work OK for automation.

Thank You

**Comment by ualex73** [comment]
This looks like an interesting request, I will investigate if I can combine multiple sensors into 1 sensor per container. In such case you will get 2 per container, a sensor and switch (combining it into the switch is too difficult, because they are different components).

**Comment by VirtualL** [comment]
Sounds great for me!
Thanks for the fast replay.

**Comment by ualex73** [comment]
Just implemented it in the master branch, with a special condition "allinone". If you add that one, it will just create 1 sensor per container with the requested attributes. I will push it to HACS somewhere next week, but would be good if you could test it.

**Comment by VirtualL** [comment]
Hi, Thanks a lot!
I replace the files( download Zip from the latest repo, and check if the file have "alleinone" option)
and I try this 2 configurations:
```
monitor_docker:
  - name: Docker
    containers:
      - unifi-controller
      - letsencrypt
      - code-server #vscode
      - mosquitto #mqtt
      - openvpn-as #VPN
    rename:
      unifi-controller: UniFi
      letsencrypt: Let's Encrypt
      code-server: VS-Code
      mosquitto: MQTT Mosquitto
      openvpn-as: Open VPN
    monitored_conditions:
      - state #for each docker container
      - status #for each docker container
      - containers_running
      - containers_total
      - containers_memory_percentage
      - containers_cpu_percentage
      - version #for each docker container
      - memory #for each docker container
      - allinone
```

```
monitor_docker:
  - name: Docker
    containers:
      - unifi-controller
      - letsencrypt
      - code-server #vscode
      - mosquitto #mqtt
      - openvpn-as #VPN
    rename:
      unifi-controller: UniFi
      letsencrypt: Let's Encrypt
      code-server: VS-Code
      mosquitto: MQTT Mosquitto
      openvpn-as: Open VPN
    monitored_conditions:
      - allinone
      - state #for each docker container
      - status #for each docker container
      - containers_running
      - containers_total
      - containers_memory_percentage
      - containers_cpu_percentage
      - version #for each docker container
      - memory #for each docker container
```

and nothing was working (Got only the "switch" for each container.
When I Remove the new "allinone" from the monitored_conditions, everything working as before (without this new feature).

Thanks
