### ISSUE TITLE
Problem during start of monitoring

### ISSUE THREAD

**Issue by darren-harrison-nz** [ualex73/monitor_docker#166]
Hi,
I'm getting a couple of errors showing up in my logs, related to a Docker container which I have, but haven't referenced.
I'm not quite sure how monitor_docker even knows about it.

> This error originated from a custom integration.
> 
> Logger: custom_components.monitor_docker.helpers
> Source: custom_components/monitor_docker/helpers.py:494
> integration: Monitor Docker (documentation, issues)
> First occurred: 12:26:08 AM (183 occurrences)
> Last logged: 3:36:09 PM
> 
> [Docker] <snip>-drupal-drupal-1: Problem during start of monitoring

The second error is about the same container.
> This error originated from a custom integration.
> 
> Logger: custom_components.monitor_docker.helpers
> Source: custom_components/monitor_docker/helpers.py:755
> integration: Monitor Docker (documentation, issues)
> First occurred: 12:26:08 AM (183 occurrences)
> Last logged: 3:36:09 PM
> 
> [Docker] <snip>-drupal-drupal-1: Container not available anymore (2a) (DockerError(404, 'No such container: <snip>-drupal-drupal-1'))

My setup specifies some other containers
```
name: Docker
containers:
  - home-assistant
  - mosquitto
  - tasmoadmin
rename:
  home-assistant: "Home Assistant"
  mosquitto: MQTT
  tasmoadmin: TasmoAdmin
monitored_conditions:
  - version
  - containers_running
  - containers_total
  - state
  - status
  - memory
scan_interval: 30
```

The errors are annoying but I can obviously ignore them, but it would be nice to figure out why and stop them.
Any ideas?

Thanks,
Darren.
