### ISSUE TITLE
Missing Sensors

### ISSUE THREAD

**Issue by PedroCavaleiro** [ualex73/monitor_docker#167]
I just configured the plugin and it works well but I'm missing some sensors.

I'm not using the allinone 

This is my current config
```yaml
monitor_docker:
  - name: Pedro's Server
    url: http://xxx.xxx.xxx.xxx:2375
    containers:
      - MQQT
      - gitlab
      - portainer
    monitored_conditions:
      - version
      - containers_running
      - containers_total
      - state
      - status
      - containers_cpu_percentage
      - containers_1cpu_percentage
      - containers_memory_percentage
      - health
      - uptime
      - image
      - cpu_percentage
      - 1cpu_percentage
      - memory_percentage
      - network_speed_up
      - network_speed_down
      - network_total_up
      - network_total_down
      - memory
      ```

For some reason these sensors don't show up. All other sensors are working just fine.
* network_speed_up
* network_speed_down
* network_total_up
* network_total_down
* memory

What can I do to help figure out this issue?
