### ISSUE TITLE
Issue with precision_network_kb 0

### ISSUE THREAD

**Issue by zoic21** [ualex73/monitor_docker#175]
Hello,

Thanks for your integration it's work perfectly, I just have an issue with precision (globaly) when I set to 0 it's seem not work. Here my conf : 

```
docker:
  monitor_docker:
    - name: Docker
      scan_interval: 60
      switchenabled: False
      buttonenabled: False
      precision_network_kb: 0
      precision_network_mb: 0
      precision_memory_percentage: 1
      precision_cpu: 1
      monitored_conditions:
        - version
        - containers_total
        - containers_running
        - 1cpu_percentage
        - memory_percentage
        - state
        - status
        - network_speed_up
        - network_speed_down 
```

For `precision_network_kb` and `precision_network_mb` when I set 1 no problem but with 0 it's stay at 1. 

Is it not allow ?

Thanks in advance
