### ISSUE TITLE
Cannot determine memory usage for container ('usage')

### ISSUE THREAD

**Issue by AndreKR** [ualex73/monitor_docker#191]
I just installed monitor_docker but no entities are created and my log is full of these messages:

```
2025-04-05 02:42:50.690 ERROR (Dummy-1) [custom_components.monitor_docker.helpers] [Americano] node-red: Cannot determine memory usage for container ('usage')
2025-04-05 02:42:50.691 ERROR (Dummy-1) [custom_components.monitor_docker.helpers] [Americano] node-red: Raw 'memory_stats' {'stats': {'active_anon': 0, 'active_file': 0, 'anon': 0, 'anon_thp': 0, 'file': 0, 'file_dirty': 0, 'file_mapped': 0, 'file_writeback': 0, 'inactive_anon': 0, 'inactive_file': 0, 'kernel_stack': 0, 'pgactivate': 0, 'pgdeactivate': 0, 'pgfault': 0, 'pglazyfree': 0, 'pglazyfreed': 0, 'pgmajfault': 0, 'pgrefill': 0, 'pgscan': 0, 'pgsteal': 0, 'shmem': 0, 'slab': 0, 'slab_reclaimable': 0, 'slab_unreclaimable': 0, 'sock': 0, 'thp_collapse_alloc': 0, 'thp_fault_alloc': 0, 'unevictable': 0, 'workingset_activate': 0, 'workingset_nodereclaim': 0, 'workingset_refault': 0}}
```

I don't even know if the messages are related to the missing entities, but something isn't right.

**Comment by ualex73** [comment]
The required memory fields are missing in your output. What type of Docker/operation system/etc are you running?

**Comment by AndreKR** [comment]
Raspberry Pi OS, completely standard Docker installation.

**Comment by AndreKR** [comment]
It's "0B / 0B" for all containers.

![Image](https://github.com/user-attachments/assets/70a301ea-904f-45f1-90ed-5d19acebc833)

**Comment by AndreKR** [comment]
I should clarify that I'm not even trying to monitor memory use, my config is just:
```
monitor_docker:
  - name: Americano
    containers_exclude:
      - chirpstack-docker-chirpstack-rest-api-1
      - chirpstack-docker-chirpstack-gateway-bridge-1
      - chirpstack-docker-chirpstack-gateway-bridge-basicstation-1
      - chirpstack-docker-postgres-1
      - chirpstack-docker-mosquitto-1
      - chirpstack-docker-redis-1
    monitored_conditions:
      - version
      - containers_running
      - containers_total
      - state
      - status
      - health
      - image
```

I don't think I should have to enable a kernel setting to use Monitor Docker on a Pi, especially when I'm not trying to monitor memory usage. Do you disagree?
