### ISSUE TITLE
Switch error

### ISSUE THREAD

**Issue by malinduta** [ualex73/monitor_docker#20]
Works to start/stop containers, but throws error when starting HA.

Configuration:
```
monitor_docker:
  - name: Docker
    containers:
      - urbackup
    rename:
      urbackup: UrBackup
    monitored_conditions:
      - version
      - containers_running
      - containers_total
      - state
      - status
      - memory
```

Log:
```
Log Details (ERROR)
Logger: homeassistant.config
Source: config.py:756
First occurred: 1:17:19 AM (1 occurrences)
Last logged: 1:17:19 AM

Invalid config for [switch]: expected a dictionary. Got True. (See ?, line ?). Please check the docs at https://www.home-assistant.io/integrations/switch
```
This is the notification:
![](https://user-images.githubusercontent.com/55548608/86264365-53a73680-bbba-11ea-9885-fefcf24f5c4d.png)
