### ISSUE TITLE
Can't use health property

### ISSUE THREAD

**Issue by mario-tux** [ualex73/monitor_docker#54]
I'm trying to enable the `health` properties for my containers. 
This is my working-old config:
```
  - name: Server
    url: tcp://192.168.200.9:2376
    certpath: /ssl/docker-certs/
    containers:
      - XXX
      - YYY
    monitored_conditions:
      - state
      - status
      - image
      - cpu_percentage
      - memory_percentage
      - memory
      - network_speed_up
      - network_speed_down
      - network_total_up
      - network_total_down
      - allinone
```

trying to add `health` to the `monitored_conditions` list I get the following on configuration validation:
```
Invalid config for [monitor_docker]: value must be one of ['1cpu_percentage', 'allinone', 'containers_1cpu_percentage', 'containers_cpu_percentage', 'containers_memory', 'containers_memory_percentage', 'containers_paused', 'containers_running', 'containers_stopped', 'containers_total', 'cpu_percentage', 'image', 'images', 'memory', 'memory_percentage', 'network_speed_down', 'network_speed_up', 'network_total_down', 'network_total_up', 'state', 'status', 'uptime', 'version'] @ data['monitor_docker'][0]['monitored_conditions'][11]. Got 'health'. (See /config/configuration.yaml, line 1035).
```

What's wrong?!
