### ISSUE TITLE
Memory Usage stats not available over TCP

### ISSUE THREAD

**Issue by drinfernoo** [ualex73/monitor_docker#64]
I have a remote Docker instance being monitored with this component, and I keep seeing these errors in my logs:
```bash
2021-05-26 21:36:49 ERROR (Thread-4) [custom_components.monitor_docker.helpers] wyzesense2mqtt: Cannot determine memory usage for container ('usage')
2021-05-26 21:36:49 ERROR (Thread-4) [custom_components.monitor_docker.helpers] wyzesense2mqtt: Raw 'memory_stats' {}
```
My YAML looks like:
```yaml
monitor_docker:
  - name: DockerPi
    url: http://192.168.1.220:2375
    containers:
      - wyzesense2mqtt
    rename:
      wyzesense2mqtt: WyzeSense2MQTT
```
Also, the sensor entities (in my case, `sensor.dockerpi_memory`, `sensor.dockerpi_memory_percent`, `sensor.dockerpi_wyzesense2mqtt_memory`, and `sensor.dockerpi_wyzesense2mqtt_memory_percent`) gets created, but with an unknown state.

**Comment by drinfernoo** [comment]
I've actually updated my YAML to *not* request these statistics:
```yaml
monitor_docker:
  - name: DockerPi
    url: http://192.168.1.220:2375
    monitored_conditions:
      - state
      - status
      - uptime
      - image
      - 1cpu_percentage
    containers:
      - wyzesense2mqtt
    rename:
      wyzesense2mqtt: WyzeSense2MQTT
```
And I'm still getting the error from my previous comment... Which makes me feel like the integration isn't respecting my new YAML?
