### ISSUE TITLE
Incompatible with Auto-Entities and Apexcharts?

### ISSUE THREAD

**Issue by IDmedia** [ualex73/monitor_docker#66]
I'm trying to create a graph over the CPU usage for all my docker containers.
Here's a minimal configuration for once container:
```
  - type: custom:apexcharts-card
    update_interval: 30s
    graph_span: 24h
    series:
      - name: Test Container
        entity: sensor.docker_test_container #Changeme
        attribute: memory
        unit: '%'
    all_series_config:
      stroke_width: 2
      float_precision: 2
    apex_config:
      chart:
        height: 300px
```

For some reason the graph fails to render with no errors whatsoever. The same works for any other entity other then those created by this integration. Anyone encountered the same issue?
