### ISSUE TITLE
Switch entity not being created

### ISSUE THREAD

**Issue by talondnb** [ualex73/monitor_docker#96]
Hi!

I don't seem to have any switch entity being created, nor any logs showing any errors relating to the integration. Here's my config snippet:

```
# Monitor Docker
monitor_docker:
  - name: RemoteDocker
    url: !secret docker_remote
    containers:
      - mc
      - mcb
```

I've also tried with the 'switchenabled: true' statement but it made no difference. The monitoring sensors, however, do appear fine. Running 1.14 and Home Assistant 2022.3.6.

Any ideas?
