### ISSUE TITLE
How to add to Lovelace dashboard?

### ISSUE THREAD

**Issue by wormvortex** [ualex73/monitor_docker#98]
I’ve downloaded via HACS, added the line to my docker config and added the info to my home assistant config.yml file but now what???

I can’t work out how to display the information on a card on the dashboard.

**Comment by mixpix405** [comment]
Just as you would any other entity. One example card would be:

```
type: entities
entities:
  - entity: sensor.docker_plex_state
  - entity: sensor.docker_plex_status
  - entity: sensor.docker_plex_memory
title: Plex Container
state_color: true
show_header_toggle: false
```
